language: python
python:
  - "3.6"

env:
  - SECRET_KEY='potato' DATABASE_NAME='rvfmdb' DATABASE_USER='' DATABASE_HOST="127.0.0.1" DATABASE_PASSWORD=''

# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements.pip
  - pip install coverage
  - pip install coveralls
  - pip install python-coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE rfvs_test;" -U postgres
  - psql -c "CREATE DATABASE rvfmdb;" -U postgres

# command to run tests
script:
  - python RVFS/manage.py makemigrations
  - python RVFS/manage.py migrate
  - coverage run RVFS/manage.py test

after_success:
  - coveralls

notifications:
email: false