# Generated by Django 2.0 on 2018-01-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
    ]
