# Generated by Django 2.0 on 2018-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180114_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
