# Generated by Django 2.0 on 2018-01-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_registration_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='resident',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='resident',
            field=models.ManyToManyField(related_name='address', to='account.Account'),
        ),
    ]
