# Generated by Django 2.0 on 2018-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180111_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='resident',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='residents',
            field=models.ManyToManyField(related_name='addresses', to='account.Account'),
        ),
    ]
