# Generated by Django 2.0 on 2018-01-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180114_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
