# Generated by Django 2.0 on 2018-01-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthday_set',
            field=models.BooleanField(default=False),
        ),
    ]
