# Generated by Django 2.0 on 2018-01-11 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20180111_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='last_name',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='resident',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
