# Generated by Django 2.0 on 2018-01-21 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_birthday_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('shipped', models.BooleanField(default=False)),
                ('tracking', models.CharField(max_length=35)),
                ('order_content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='resident',
        ),
        migrations.AddField(
            model_name='account',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='account.ShippingInfo'),
        ),
        migrations.AddField(
            model_name='account',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='account.Order'),
        ),
    ]
