# Generated by Django 2.0 on 2018-01-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180121_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='purchase_history',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='saved_products',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='saved_services',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='service_history',
            field=models.TextField(default=''),
        ),
    ]
