# Generated by Django 2.0 on 2018-01-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180121_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addresses',
        ),
        migrations.AddField(
            model_name='account',
            name='main_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='name',
            field=models.CharField(default='home', max_length=50, verbose_name='Location Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
