# Generated by Django 2.0 on 2018-01-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_shippinginfo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_address_delete',
            field=models.BooleanField(default=False),
        ),
    ]
