# Generated by Django 2.0 on 2018-02-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180131_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.ShippingInfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking',
            field=models.CharField(default='', max_length=35),
        ),
    ]
