# Generated by Django 2.0 on 2018-02-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_slideshowimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowimage',
            name='image',
            field=models.ImageField(upload_to='slides'),
        ),
    ]
