# Generated by Django 2.0 on 2018-02-11 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180205_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serv_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_service', to='account.ShippingInfo'),
        ),
    ]
