# Generated by Django 2.0 on 2018-02-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_order_serv_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment',
            field=models.CharField(default='', max_length=40),
        ),
    ]
