# Generated by Django 2.0 on 2018-02-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='address2',
            field=models.CharField(default='', max_length=250, verbose_name='Address line 2'),
        ),
    ]
