# Generated by Django 2.0 on 2018-09-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20180909_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='purchase_history',
        ),
        migrations.RemoveField(
            model_name='account',
            name='service_history',
        ),
        migrations.RemoveField(
            model_name='order',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='serv_address',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
