# Generated by Django 2.0 on 2018-09-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180912_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
