# Generated by Django 2.0 on 2018-09-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_account_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
