# Generated by Django 2.0 on 2018-09-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20180917_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cell_number',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='account',
            name='home_number',
            field=models.CharField(default='(000)-000-0000', max_length=14),
        ),
    ]
