# Generated by Django 2.0 on 2018-09-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20180924_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='active_discount',
        ),
    ]
