# Generated by Django 2.0 on 2018-09-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_account_active_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_code',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
