# Generated by Django 2.0 on 2018-12-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20181111_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pre_order',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='pre_order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Address line 2'),
        ),
    ]
