# Generated by Django 2.1.5 on 2019-02-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20181230_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(default='(000)-000-0000', max_length=14),
        ),
    ]
