# Generated by Django 2.1.5 on 2019-02-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_order_recipient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
