# Generated by Django 2.1.5 on 2019-03-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_order_amount_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Order')),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            bases=('account.order',),
        ),
    ]
