# Generated by Django 2.0 on 2018-01-14 06:42

from django.db import migrations, models
import multiselectfield.db.fields
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images')),
                ('published', models.CharField(choices=[('PB', 'public'), ('PV', 'private')], default='PV', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('length', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16)], default='', max_length=150)),
                ('diamiter', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1/8', '1/8'), ('1/4', '1/4'), ('3/8', '3/8'), ('1/2', '1/2'), ('5/8', '5/8')], default='', max_length=150)),
                ('decription', models.TextField(default='')),
                ('shipping_info', models.TextField(blank=True, max_length=180)),
                ('color', models.TextField(blank=True, max_length=500)),
                ('extra_options', models.TextField(blank=True, max_length=500)),
                ('Tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images')),
                ('published', models.CharField(choices=[('PB', 'public'), ('PV', 'private')], default='PV', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('decription', models.TextField(default='', max_length=500)),
                ('limitations', models.TextField(default='', max_length=500)),
                ('commision_fee', models.IntegerField(blank=True, default=0)),
                ('price_range', models.CharField(default='', max_length=15)),
                ('extras', models.TextField(blank=True, max_length=500)),
                ('warning', models.TextField(blank=True, max_length=500)),
                ('Tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='slides')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
