# Generated by Django 2.0 on 2018-01-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='extra_options',
            new_name='extras',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Tags',
            new_name='tags',
        ),
    ]
