# Generated by Django 2.0 on 2018-01-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180118_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diamiter',
            field=models.TextField(blank=True, default='1/8 stock=0, 1/4 stock=0, 3/8 stock=0, 1/2 stock=0, 5/8 stock=0', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.TextField(blank=True, default='4 stock=0, 5 stock=0, 6 stock=0, 7 stock=0, 8 stock=0, 9 stock=0, 10 stock=0, 11 stock=0, 12 stock=0, 13 stock=0, 14 stock=0, 15 stock=0, 16 stock=0, ', max_length=150),
        ),
    ]
