# Generated by Django 2.0 on 2018-01-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180118_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_knife',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_knife',
            field=models.BooleanField(default=False),
        ),
    ]
