# Generated by Django 2.0 on 2018-01-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180118_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='diamiter',
            new_name='diameter',
        ),
    ]
