# Generated by Django 2.0 on 2018-01-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180119_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_pictures',
            field=models.BooleanField(default=False),
        ),
    ]
