# Generated by Django 2.0 on 2018-01-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180119_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='commision_fee',
            new_name='commission_fee',
        ),
    ]
