# Generated by Django 2.0 on 2018-01-31 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180125_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_info',
        ),
    ]
