# Generated by Django 2.0 on 2018-02-05 03:02

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_shipping_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='service_images')),
            ],
        ),
    ]
