# Generated by Django 2.0 on 2018-02-11 07:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180205_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1/8"', '1/8"'), ('1/4"', '1/4"'), ('3/8"', '3/8"'), ('1/2"', '1/2"'), ('5/8"', '5/8"')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('4"', '4"'), ('5"', '5"'), ('6"', '6"'), ('7"', '7"'), ('8"', '8"'), ('9"', '9"'), ('10"', '10"'), ('11"', '11"'), ('12"', '12"'), ('13"', '13"'), ('14"', '14"'), ('15"', '15"'), ('16"', '16"')], default='', max_length=150),
        ),
    ]
