# Generated by Django 2.0 on 2018-02-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180211_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userserviceimage',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
