# Generated by Django 2.0 on 2018-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_userserviceimage_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserviceimage',
            name='image',
            field=models.ImageField(upload_to='service_images'),
        ),
    ]
