# Generated by Django 2.0 on 2018-02-12 14:28

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180212_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserviceimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='service_images'),
        ),
    ]
