# Generated by Django 2.0 on 2018-08-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180212_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='catagories',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='tags',
            new_name='catagories',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
