# Generated by Django 2.0 on 2018-09-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20180828_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='catagories',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_knife',
        ),
        migrations.RemoveField(
            model_name='service',
            name='requires_address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='requires_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='requires_pictures',
        ),
        migrations.AddField(
            model_name='service',
            name='blurb',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='limitations',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_range',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
