# Generated by Django 2.0 on 2018-09-12 18:32

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20180909_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagories',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
