# Generated by Django 2.0 on 2018-09-17 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Creator',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
