# Generated by Django 2.0 on 2018-09-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20180917_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Creator',
            new_name='creator',
        ),
    ]
