# Generated by Django 2.0 on 2018-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20180927_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
