# Generated by Django 2.0 on 2018-10-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_service_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_width',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
