# Generated by Django 2.0 on 2018-11-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20181031_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('code_type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=10)),
                ('code_state', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
