# Generated by Django 2.0 on 2018-11-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='prod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='prod_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
