# Generated by Django 2.0 on 2018-01-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180107_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderImages',
            new_name='SliderImage',
        ),
    ]
