# Generated by Django 2.0 on 2018-01-07 03:00

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='catagories',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='service',
            name='commision_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='extras',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='limitations',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='price_range',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='service',
            name='warning',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='decription',
            field=models.TextField(default='', max_length=500),
        ),
    ]
