# Generated by Django 2.0 on 2018-01-07 10:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('services', '0002_auto_20180107_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='catagories',
        ),
        migrations.AddField(
            model_name='service',
            name='Tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
